"""empty message

Revision ID: 0b6937f041c0
Revises: 37418af0ab2d
Create Date: 2019-06-20 17:55:33.575000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b6937f041c0'
down_revision = '37418af0ab2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vcenter_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('mor_name', sa.String(length=128), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('dc_name', sa.String(length=128), nullable=True),
    sa.Column('dc_mor_name', sa.String(length=128), nullable=True),
    sa.Column('cpu_nums', sa.Integer(), nullable=True),
    sa.Column('cpu_capacity', sa.Integer(), nullable=True),
    sa.Column('used_cpu', sa.Integer(), nullable=True),
    sa.Column('memory', sa.BigInteger(), nullable=True),
    sa.Column('used_memory', sa.BigInteger(), nullable=True),
    sa.Column('capacity', sa.BigInteger(), nullable=True),
    sa.Column('used_capacity', sa.BigInteger(), nullable=True),
    sa.Column('host_nums', sa.Integer(), nullable=True),
    sa.Column('vm_nums', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('VCenter_clusters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VCenter_clusters',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=128), nullable=True),
    sa.Column('mor_name', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=128), nullable=True),
    sa.Column('platform_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('dc_name', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=128), nullable=True),
    sa.Column('dc_mor_name', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=128), nullable=True),
    sa.Column('cpu_nums', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('used_cpu', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('memory', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('used_memory', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('capacity', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('cpu_capacity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('host_nums', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('used_capacity', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('vm_nums', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8_unicode_ci',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('vcenter_clusters')
    # ### end Alembic commands ###
