"""empty message

Revision ID: 1f1d50484ac9
Revises: 33607e089161
Create Date: 2019-06-21 16:18:56.058000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1d50484ac9'
down_revision = '33607e089161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licenses', sa.Column('platform_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licenses', 'platform_id')
    # ### end Alembic commands ###
