"""empty message

Revision ID: 33607e089161
Revises: 0b6937f041c0
Create Date: 2019-06-21 15:21:49.442000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33607e089161'
down_revision = '0b6937f041c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vcenter_host', sa.Column('cluster_mor_name', sa.String(length=128), nullable=True))
    op.add_column('vcenter_host', sa.Column('cluster_name', sa.String(length=128), nullable=True))
    op.add_column('vcenter_host', sa.Column('dc_mor_name', sa.String(length=128), nullable=True))
    op.add_column('vcenter_host', sa.Column('dc_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vcenter_host', 'dc_name')
    op.drop_column('vcenter_host', 'dc_mor_name')
    op.drop_column('vcenter_host', 'cluster_name')
    op.drop_column('vcenter_host', 'cluster_mor_name')
    # ### end Alembic commands ###
