"""empty message

Revision ID: 7d0266ed8abe
Revises: 5749754567ec
Create Date: 2019-06-12 15:22:53.719000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d0266ed8abe'
down_revision = '5749754567ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vcenter_resource_pool', sa.Column('parent_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vcenter_resource_pool', 'parent_id')
    # ### end Alembic commands ###
