"""empty message

Revision ID: 8cfc0872a1a1
Revises: e61fe1d59e75
Create Date: 2019-06-20 11:57:18.445000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8cfc0872a1a1'
down_revision = 'e61fe1d59e75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VCenter_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('mor_name', sa.String(length=128), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('dc_name', sa.String(length=128), nullable=True),
    sa.Column('dc_mor_name', sa.String(length=128), nullable=True),
    sa.Column('cpu_nums', sa.Integer(), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('cpu_mhz', sa.Integer(), nullable=True),
    sa.Column('used_cpu', sa.Integer(), nullable=True),
    sa.Column('memory', sa.BigInteger(), nullable=True),
    sa.Column('used_memory', sa.BigInteger(), nullable=True),
    sa.Column('capacity', sa.BigInteger(), nullable=True),
    sa.Column('free_capacity', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vcenter_datacenter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('mor_name', sa.String(length=128), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('host_nums', sa.Integer(), nullable=True),
    sa.Column('vm_nums', sa.Integer(), nullable=True),
    sa.Column('cluster_nums', sa.Integer(), nullable=True),
    sa.Column('network_nums', sa.Integer(), nullable=True),
    sa.Column('datastore_nums', sa.Integer(), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('cpu_mhz', sa.Integer(), nullable=True),
    sa.Column('used_cpu', sa.Integer(), nullable=True),
    sa.Column('memory', sa.BigInteger(), nullable=True),
    sa.Column('used_memory', sa.BigInteger(), nullable=True),
    sa.Column('capacity', sa.BigInteger(), nullable=True),
    sa.Column('free_capacity', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'vcenter_host', sa.Column('memory', sa.BigInteger(), nullable=True))
    op.add_column(u'vcenter_host', sa.Column('network_nums', sa.Integer(), nullable=True))
    op.add_column(u'vcenter_host', sa.Column('used_memory', sa.BigInteger(), nullable=True))
    op.add_column(u'vcenter_host', sa.Column('vm_nums', sa.Integer(), nullable=True))
    op.drop_column(u'vcenter_host', 'used_ram')
    op.drop_column(u'vcenter_host', 'ram')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'vcenter_host', sa.Column('ram', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column(u'vcenter_host', sa.Column('used_ram', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.drop_column(u'vcenter_host', 'vm_nums')
    op.drop_column(u'vcenter_host', 'used_memory')
    op.drop_column(u'vcenter_host', 'network_nums')
    op.drop_column(u'vcenter_host', 'memory')
    op.drop_table('vcenter_datacenter')
    op.drop_table('VCenter_clusters')
    # ### end Alembic commands ###
