"""empty message

Revision ID: 91b1aea141d7
Revises: 4892282ab07c
Create Date: 2019-05-08 14:29:44.992000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b1aea141d7'
down_revision = '4892282ab07c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vcenter_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('mor_name', sa.String(length=32), nullable=True),
    sa.Column('vm_uuid', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_parent_id', sa.Integer(), nullable=True),
    sa.Column('current', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vcenter_snapshot')
    # ### end Alembic commands ###
