"""empty message

Revision ID: bf0abd9691b1
Revises: c30e8c03c6ee
Create Date: 2019-04-26 15:10:30.512000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0abd9691b1'
down_revision = 'c30e8c03c6ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vcenter_datastore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.String(length=255), nullable=True),
    sa.Column('used_capacity', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=55), nullable=True),
    sa.Column('version', sa.String(length=55), nullable=True),
    sa.Column('uuid', sa.Integer(), nullable=True),
    sa.Column('ssd', sa.Boolean(), nullable=False),
    sa.Column('local', sa.Boolean(), nullable=False),
    sa.Column('host', sa.String(length=55), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vcenter_disk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vm_uuid', sa.String(length=64), nullable=False),
    sa.Column('disk_uuid', sa.String(length=64), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=32), nullable=True),
    sa.Column('disk_size', sa.String(length=64), nullable=True),
    sa.Column('disk_type', sa.Integer(), nullable=True),
    sa.Column('sharing', sa.String(length=16), nullable=True),
    sa.Column('disk_file', sa.String(length=64), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=True),
    sa.Column('iops', sa.String(length=16), nullable=True),
    sa.Column('cache', sa.Integer(), nullable=True),
    sa.Column('disk_mode', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vcenter_disk')
    op.drop_table('vcenter_datastore')
    # ### end Alembic commands ###
