"""empty message

Revision ID: c30e8c03c6ee
Revises: 33b18cb40f99
Create Date: 2019-04-24 09:54:07.641000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30e8c03c6ee'
down_revision = '33b18cb40f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vcenter_network_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('vm_uuid', sa.String(length=255), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('mac', sa.String(length=255), nullable=True),
    sa.Column('network_port_group', sa.String(length=255), nullable=True),
    sa.Column('address_type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vcenter_network_device')
    # ### end Alembic commands ###
