"""empty message

Revision ID: cedf9a228930
Revises: 5242b651f92e
Create Date: 2019-05-20 16:56:42.884000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cedf9a228930'
down_revision = '5242b651f92e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vcenter_instance', sa.Column('create_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vcenter_instance', 'create_at')
    # ### end Alembic commands ###
