"""update

Revision ID: e5af106b66b2
Revises: cedf9a228930
Create Date: 2019-06-06 13:37:30.817921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5af106b66b2'
down_revision = 'cedf9a228930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vcenter_network_distributed_switch_port_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('mor_name', sa.String(length=255), nullable=True),
    sa.Column('dc_name', sa.String(length=255), nullable=True),
    sa.Column('dc_mor_name', sa.String(length=255), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('switch', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'vcenter_network_port_group', sa.Column('host', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'vcenter_network_port_group', 'host')
    op.drop_table('vcenter_network_distributed_switch_port_group')
    # ### end Alembic commands ###
